//
//  UIColor+SILColors.m
//  Silicon Labs Bluetooth Smart App
//
//  Generated by Zeplin (by colden on 2/3/15).
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

#import "UIColor+SILColors.h"

@implementation UIColor (SILColors)

#pragma mark - Brand / Accent (theme‑dependent)

+ (UIColor *)sil_siliconLabsRedColor {
    return [UIColor appPrimaryBrand];
}

+ (UIColor *)sil_regularBlueColor {
    return [UIColor appPrimaryBrand];
}

+ (UIColor *)sil_strongBlueColor {
    return [UIColor appStrongAccent];
}

+ (UIColor *)sil_lightBlueColor {
    return [UIColor appLightAccent];
}

#pragma mark - Text (routed through palette)

+ (UIColor *)sil_primaryTextColor {
    return [UIColor appPrimaryText];
}

+ (UIColor *)sil_subtitleTextColor {
    return [UIColor appSubtleText];
}

+ (UIColor *)sil_masalaColor {
    return [UIColor appMasalaText];
}

+ (UIColor *)sil_masala50pcColor {
    return [UIColor appMasala50pcText];
}

#pragma mark - Backgrounds (routed through palette)

+ (UIColor *)sil_backgroundColor {
    return [UIColor appBackground];
}

+ (UIColor *)sil_secondaryBackgroundColor {
    return [UIColor appSecondaryBackground];
}

+ (UIColor *)sil_cardBackgroundColor {
    return [UIColor appCardBackground];
}

+ (UIColor *)sil_disableCardBgColor {
    return [UIColor appDisableCardBackground];
}

+ (UIColor *)sil_bgWhiteColor {
    return [UIColor appBgWhite];
}

+ (UIColor *)sil_bgGreyColor {
    return [UIColor appBgGrey];
}

#pragma mark - Greys / Borders (routed through palette)

+ (UIColor *)sil_lineGreyColor {
    return [UIColor appLineGrey];
}

+ (UIColor *)sil_lightGreyColor {
    return [UIColor appLightGrey];
}

+ (UIColor *)sil_refreshGreyColor {
    return [UIColor appRefreshGrey];
}

+ (UIColor *)sil_silverColor {
    return [UIColor appSilver];
}

+ (UIColor *)sil_silverChaliceColor {
    return [UIColor appSilverChalice];
}

+ (UIColor *)sil_boulderColor {
    return [UIColor appBoulder];
}

#pragma mark - Status

+ (UIColor *)sil_yellowColor {
    return [UIColor appWarning];
}

+ (UIColor *)sil_greenColor {
    return [UIColor appSuccess];
}

@end
